"""
settings.py
CLASSIFICATION: V11.0 Central Configuration File
GOAL: Acts as the single source of truth for all configuration parameters,
      script pointers, and data contract keys for the entire V11.0 suite.

This module is the core of the V11 Hardening Protocol. Its purpose is to
enforce a strict, explicit, and machine-readable data contract across all
decoupled components (Orchestrator, Worker, Validator, API). By centralizing
these definitions, we eliminate the brittle, hardcoded file paths and keys
that led to data contract drift and pipeline deadlocks in previous versions.

All other scripts MUST import their configuration from this file.
"""

import os

# --- V11.0 ARCHITECTURE: SCRIPT POINTERS ---
# Defines the executable components for the new decoupled architecture.
# This ensures the orchestrator can be reconfigured without code changes.
WORKER_SCRIPT = "worker_sncgl_sdg.py"
VALIDATOR_SCRIPT = "validation_pipeline.py"

# --- V11.0 DATA CONTRACT: UNIFIED HASHING MANDATE ---
# These keys define the non-negotiable data contract enforced across all
# simulation artifacts (HDF5 files) and provenance reports (JSON files).
# This uniformity is critical for the Hunter's parsing logic and ensures
# auditable data flow.

# The single, authoritative key for identifying a unique simulation run.
# Generated by the core engine and passed to all downstream components.
HASH_KEY = "job_uuid"

# The primary scientific fidelity metric, measuring the alignment of the
# simulation's spectral output with the log-prime attractor hypothesis.
SSE_METRIC_KEY = "log_prime_sse"

# The primary geometric stability metric, measuring the L2 norm of the
# Hamiltonian constraint violation from the SDG solver. This is the core
# metric for resolving the V10.0 "Geometric Crisis".
STABILITY_METRIC_KEY = "sdg_h_norm_l2"

# --- EVOLUTIONARY HUNT PARAMETERS ---
# Default parameters for the Hunter's evolutionary search. These can be
# overridden by the Control Hub API.
NUM_GENERATIONS = 10
POPULATION_SIZE = 10

# --- FILE PATHS AND DIRECTORIES ---
BASE_DIR = os.getcwd()
CONFIG_DIR = os.path.join(BASE_DIR, "input_configs")
PROVENANCE_DIR = os.path.join(BASE_DIR, "provenance_reports")
DATA_DIR = os.path.join(BASE_DIR, "simulation_data")
STATUS_FILE = os.path.join(BASE_DIR, "status.json")
